apiVersion: v1
data:
  mapAccounts: '[]'
  mapRoles: '[{"rolearn":"arn:aws:iam::814445629751:role/k8sCdkStack-EksclusterMastersRoleD85283BE-1H11KBAHF7MKI","username":"arn:aws:iam::814445629751:role/k8sCdkStack-EksclusterMastersRoleD85283BE-1H11KBAHF7MKI","groups":["system:masters"]},{"rolearn":"arn:aws:iam::814445629751:role/k8sCdkStack-EksclusterfargateprofiledefaultPodExec-EM86FI1443DD","username":"system:node:{{SessionName}}","groups":["system:bootstrappers","system:nodes","system:node-proxier"]},{"rolearn":"arn:aws:iam::814445629751:role/k8sCdkStack-EksclusterNodegroupeksnodegropNodeGrou-1JNK5IEVI00PL","username":"system:node:{{EC2PrivateDNSName}}","groups":["system:bootstrappers","system:nodes"]}]'
  mapUsers: '[]'
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapAccounts":"[]","mapRoles":"[{\"rolearn\":\"arn:aws:iam::814445629751:role/k8sCdkStack-EksclusterMastersRoleD85283BE-1H11KBAHF7MKI\",\"username\":\"arn:aws:iam::814445629751:role/k8sCdkStack-EksclusterMastersRoleD85283BE-1H11KBAHF7MKI\",\"groups\":[\"system:masters\"]},{\"rolearn\":\"arn:aws:iam::814445629751:role/k8sCdkStack-EksclusterfargateprofiledefaultPodExec-EM86FI1443DD\",\"username\":\"system:node:{{SessionName}}\",\"groups\":[\"system:bootstrappers\",\"system:nodes\",\"system:node-proxier\"]},{\"rolearn\":\"arn:aws:iam::814445629751:role/k8sCdkStack-EksclusterNodegroupeksnodegropNodeGrou-1JNK5IEVI00PL\",\"username\":\"system:node:{{EC2PrivateDNSName}}\",\"groups\":[\"system:bootstrappers\",\"system:nodes\"]}]","mapUsers":"[]"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"aws.cdk.eks/prune-c81970a97dd38c59964ed21f27c3697c8b033ddd1b":""},"name":"aws-auth","namespace":"kube-system"}}
  creationTimestamp: "2021-04-05T04:48:33Z"
  labels:
    aws.cdk.eks/prune-c81970a97dd38c59964ed21f27c3697c8b033ddd1b: ""
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data: {}
    manager: vpcLambda
    operation: Update
    time: "2021-04-05T04:49:23Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        f:mapAccounts: {}
        f:mapRoles: {}
        f:mapUsers: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:aws.cdk.eks/prune-c81970a97dd38c59964ed21f27c3697c8b033ddd1b: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2021-04-05T04:51:27Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1404"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 60d3c9d2-e616-4a73-973d-a70d96e042e8
