version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install -g npm@7.5.6
      - npm ci

  pre_build:
    commands:
      - npm run build
      - npm run test

  build:
    commands:
      - npx cdk diff || true
      - npx cdk deploy --all --require-approval "never"
      - echo > .success

artifacts:
  files:
    - '**/*'
